[[headers]]
for = "/*"
X-Clacks-Overhead = "GNU Terry Pratchett"

[[redirects]]
from = "/"
to = "/en/swears/index.html"
status = 200
force = true

[[redirects]]
from = "/en"
to = "/en/swears/index.html"
status = 200
force = true

[[redirects]]
from = "/de"
to = "/de/swears/index.html"
status = 200
force = true

[[redirects]]
from = "/pl"
to = "/pl/swears/index.html"
status = 200
force = true
